name: Tests

on: [push]
  # push:
    # branches:
    #   - hw*

env:
  GO111MODULE: "on"

jobs:
  lint_go:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Go Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45
          working-directory: ${{ env.BRANCH }}

  lint_markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Markdown Linter
        uses: avto-dev/markdown-lint@v1
        with:
          args: "."

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18

      - name: Check out code
        uses: actions/checkout@v2

      - name: Unit tests
        run: go test -v -count=1 -race -timeout=10m ./...
        working-directory: ${{ env.BRANCH }}
