name: Lint

on: [push]

jobs:
  lint_go:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Go Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45

  lint_markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Markdown Linter
        uses: avto-dev/markdown-lint@v1
        with:
          args: "."
