name: Test

on:
  push:
    branches:
      - hw*

env:
  GO111MODULE: "on"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18

      - name: Test
        run: go test -v -cover -timeout 10m -parallel 2 ./...
        working-directory: ${{ github.head_ref }}
